run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: youtube-deck-go

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor

  exclude-files:
    - ".*_templ\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
