// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Subscription struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	YoutubeID    string         `json:"youtube_id"`
	Type         string         `json:"type"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	LastChecked  sql.NullTime   `json:"last_checked"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Position     sql.NullInt64  `json:"position"`
	Active       sql.NullInt64  `json:"active"`
	PageToken    sql.NullString `json:"page_token"`
	HideShorts   sql.NullInt64  `json:"hide_shorts"`
}

type Video struct {
	ID             int64          `json:"id"`
	SubscriptionID int64          `json:"subscription_id"`
	YoutubeID      string         `json:"youtube_id"`
	Title          string         `json:"title"`
	ThumbnailUrl   sql.NullString `json:"thumbnail_url"`
	Duration       sql.NullString `json:"duration"`
	PublishedAt    sql.NullTime   `json:"published_at"`
	Watched        sql.NullInt64  `json:"watched"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}
